#!/bin/bash

folder=`cat ~/Pictures/wallpaperfolder.txt`
wallpaper=$(find $folder  -type f | shuf -n 1)

wallpaper-rand() {
    killall swaybg
    sleep 0.05
    swaybg -i  $wallpaper -o '*' &

notify-send -t 3000 "New wallpaper: " $wallpaper
disown
}

wallpaper-rand
